### ISSUE TITLE
Bug issue

### ISSUE THREAD

**Issue by Smu-Tan** [jxhe/unified-parameter-efficient-tuning#25]
Hi, I got a bug when reproducing the translation task. Could you let me know if there are any possible solutions? It seems the problem is from dynamic_batching in petl. Thank you in advance!

`TypeError: Wrong key type: '1609' of type '<class 'numpy.int64'>'. Expected one of int, slice, range, str or Iterable.`

**Main packages:**

petl                     1.7.12
datasets                 1.11.0
fairseq                  0.12.2
hydra-core               1.0.7
jedi                     0.18.2
multiprocess             0.70.12.2
numpy                    1.24.2
pandas                   1.5.3
sacrebleu                1.5.1
sacremoses               0.0.53
tokenizers               0.10.3
torch                    1.9.0+cu111
torchaudio               0.9.0
torchvision              0.10.0+cu111
tornado                  6.2
tqdm                     4.65.0
transformers             4.9.0.dev0   /unify-parameter-efficient-tuning

Errors:
```
***** Running training *****
  Num examples = 3000
  Num Epochs = 30
  Instantaneous batch size per device = 10
  Total train batch size (w. parallel, distributed & accumulation) = 40
  Gradient Accumulation steps = 4
  Total optimization steps = 210
Traceback (most recent call last):
  File "/ivi/ilps/personal/stan1/unify-parameter-efficient-tuning/examples/pytorch/translation/run_translation.py", line 718, in <module>
    main()
  File "/ivi/ilps/personal/stan1/unify-parameter-efficient-tuning/examples/pytorch/translation/run_translation.py", line 630, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/ivi/ilps/personal/stan1/unify-parameter-efficient-tuning/src/transformers/trainer.py", line 1275, in train
    for step, inputs in enumerate(epoch_iterator):
  File "/home/stan1/anaconda3/envs/adapter/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/stan1/anaconda3/envs/adapter/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/stan1/anaconda3/envs/adapter/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/stan1/anaconda3/envs/adapter/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ivi/ilps/personal/stan1/unify-parameter-efficient-tuning/./petl/dynamic_batching.py", line 167, in __getitem__
    return self.dataset.__getitem__(item)
  File "/home/stan1/anaconda3/envs/adapter/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2709, in __getitem__
    return self._getitem(key)
  File "/home/stan1/anaconda3/envs/adapter/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2693, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/home/stan1/anaconda3/envs/adapter/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 583, in query_table
    _raise_bad_key_type(key)
  File "/home/stan1/anaconda3/envs/adapter/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 45, in _raise_bad_key_type
    raise TypeError(
TypeError: Wrong key type: '1609' of type '<class 'numpy.int64'>'. Expected one of int, slice, range, str or Iterable.

```

**Comment by Smu-Tan** [comment]
It seems the issue can be solved by changing some code in the torch even though it's a bit nasty. 

change `data = [self.dataset[idx] for idx in possibly_batched_index]` to `data = [self.dataset[idx.item()] if type(idx)!=int else self.dataset[idx] for idx in possibly_batched_index]`
